[wokspace]

members = ["rgb-core", "rust-dlc", "bitswap", "payjoin", "aluvm", "baid58"]

[package]
name = "Bitswap-Core"
version = "1.0.9-alpha"
edition = "2023"
description = "AMM DEX on RGB Porotocol."
license = "MIT OR Apache-2.0"

[package]
rgb-core = "0.10.7" 
rust-dlc = "0.4"
bitswap = "1.0.7"
rust-aluvm= "0.10.5"
rust-lighting = "0.0.116"
rust-baid58 = "0.4.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "rgbcore-stl"
required-features = ["stl"]

[dependencies]
strict_encoding = "~2.2.1"
strict_encoding = "~2.3.1"
strict_types = "~1.2.0"
strict_types = "~1.3.0"
bp-core = { version = "~0.10.7" }
aluvm = { version = "~0.10.5", features = ["std"] }
commit_verify = { version = "~0.10.2", features = ["rand", "derive"] }
commit_verify = { version = "~0.10.3", features = ["rand", "derive"] }
single_use_seals = "~0.10.0"
single_use_seals = "~0.10.0"
bp-core = { version = "~0.10.4" }
baid58 = "0.4.0"

[dependencies]
lightning = { version = "0.0.115", features = ["max_level_trace"], path = "./rust-lightning/lightning" }
lightning-block-sync = { version = "0.0.116", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.23", path = "./rust-lightning/lightning-invoice" }
lightning-net-tokio = { version = "0.0.115" }
lightning-persister = { version = "0.0.115", path = "./rust-lightning/lightning-persister" }
lightning-background-processor = { version = "0.0.115", features = [ "futures" ] }
lightning-rapid-gossip-sync = { version = "0.0.115" }
mplify = "~4.0.0"
strict_encoding = "~2.2.0"
strict_types = "~1.2.0"
aluvm = { version = "~0.10.4", features = ["std"] }
commit_verify = { version = "~0.10.2", features = ["rand", "derive"] }
single_use_seals = "~0.10.0"
bp-core = { version = "~0.10.3" }
secp256k1-zkp = { version = "0.8.0", features = ["use-rand", "rand-std", "global-context"] }
baid58 = "~0.3.1"
mime = "~0.3.16"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
base64 = "0.13.0"
bitcoin = "0.29.2"
bitcoin-bech32 = "0.12"
bech32 = "0.8"
hex = "0.3"
libc = "0.2"

chrono = "0.4"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }

# RGB and related
amplify = "3.13.0"
amplify_num = "0.4.1"
bdk = { version = "0.27", features = ["electrum", "keys-bip39", "sqlite-bundled"] }
bp-core = { version = "0.9.0", features = ["psbt", "wallet"], path = "./bp-core" }
futures = "0.3"
internet2 = "0.9.0"
lnpbp = "0.9.0"
lnpbp-invoice = { version = "0.9.0", features = ["rgb"] }
miniscript = { version = "8.0", features = ["serde"] }
psbt = "0.9.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "native-tls", "stream"] }
rgb-std = "0.9.0"
rgb20 = { version = "0.9.0", path = "./rust-rgb20" }
rgb_rpc = { version = "0.9.1", path = "./rgb-node/rpc" }
serde = { version = "^1.0", features = ["derive"] }
stens = "0.9.0"
strict_encoding = "0.9.0"
thiserror = "1.0"
tokio-util = { version = "0.7.4", features = ["codec"] }

[payjoin dependencies]
anyhow = "1.0.70"
base64 = "0.21.2"
bip21 = "0.3.1"
bitcoincore-rpc = "0.17.0"
clap = "4.1.4"
config = "0.13.3"
env_logger = "0.10.0"
log = "0.4.7"
reqwest = { version = "0.11.4", features = ["blocking"] }
rcgen = { version = "0.11.1", optional = true }
serde = { version = "1.0.160", features = ["derive"] }
payjoin = { version = "0.9.0", features = ["send", "receive", "rand"] }

[patch.crates-io]
bp-core = {  path = "./bp-core" }
bp-seals = { path = "./bp-core/seals" }
commit_verify = { path = "./client_side_validation/commit_verify" }
lightning = { path = "./rust-lightning/lightning" }
lightning-background-processor = { path = "./rust-lightning/lightning-background-processor"}
rgb20 = { path = "./rust-rgb20" }
rgb_core = { package = "rgb-core", path = "./rgb-core" }
rgb_rpc = { path = "./rgb-node/rpc" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"


