[wokspace]

members = ["rgb-core", "rust-dlc", "bitswap", "payjoin", "aluvm", "baid58"]

[package]
name = "Bitswap-Core"
version = "1.0.11-alpha"
edition = "2023"
description = "AMM DEX on RGB Porotocol."
license = "Business Source License 1.1"

[memmbers]
swap = "algorithm, dlc"
dlc = "message"
algorithm = "amm contract"
ldk = "invoice"

[dex.dependencies]
swap = "pairs, ldk"
bp-core = "tapret, op"


[core_functions]
rgb-core = "0.10.8" 
rust-dlc = "0.4"
bitswap = "1.0.11"
rust-aluvm = "0.10.5"
rust-lighting = "0.0.117"
rust-baid58 = "0.4.0"
rgb-wallet = "0.10.8"
carbonado ="0.3.3"
bp-std = "0.11.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "rgbcore-stl"
required-features = ["stl"]

[dependencies]
strict_encoding = "~2.2.1"
strict_encoding = "~2.3.1"
strict_types = "~1.2.0"
strict_types = "~1.3.0"
bp-core = { version = "~0.10.7" }
aluvm = { version = "~0.10.5", features = ["std"] }
commit_verify = { version = "~0.10.2", features = ["rand", "derive"] }
commit_verify = { version = "~0.10.3", features = ["rand", "derive"] }
single_use_seals = "~0.10.0"
single_use_seals = "~0.10.0"
bp-core = { version = "~0.10.4" }
baid58 = "0.4.0"

[dependencies]
lightning = { version = "0.0.117", path = "../lightning", features = ["_test_utils"] }
lightning-invoice = { version = "0.25.0", path = "../lightning-invoice" }
lightning-persister = { version = "0.0.117", path = "../lightning-persister" }
lightning-block-sync = { version = "0.0.116", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.23", path = "./rust-lightning/lightning-invoice" }
lightning-net-tokio = { version = "0.0.115" }
lightning-persister = { version = "0.0.115", path = "./rust-lightning/lightning-persister" }
lightning-background-processor = { version = "0.0.115", features = [ "futures" ] }
lightning-rapid-gossip-sync = { version = "0.0.115" }

[rgb core]
amplify = "~4.5.0"
strict_encoding = "~2.6.1"
strict_types = "~1.6.3"
aluvm = { version = "~0.10.6", features = ["std"] }
commit_verify = { version = "~0.10.6", features = ["rand", "derive"] }
single_use_seals = "~0.10.1"
bp-core = { version = "~0.10.10" }
secp256k1-zkp = { version = "0.9.2", features = ["rand", "rand-std", "global-context"] }
baid58 = "~0.4.4"
mime = "~0.3.17"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
base64 = "0.13.0"
bitcoin = "0.29.2"
bitcoin-bech32 = "0.12"
bech32 = "0.8"
hex = "0.3"
libc = "0.2"

chrono = "0.4"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }


[features]
default = []
all = ["stl", "serde"]
stl = ["commit_verify/stl", "bp-core/stl", "aluvm/stl"]
serde = [
    "serde_crate",
    "amplify/serde",
    "strict_encoding/serde",
    "strict_types/serde",
    "commit_verify/serde",
    "bp-core/serde",
    "aluvm/serde",
    "secp256k1-zkp/use-serde"
]

# RGB and related
amplify = "3.13.0"
amplify_num = "0.4.1"
bdk = { version = "0.27", features = ["electrum", "keys-bip39", "sqlite-bundled"] }
bp-core = { version = "0.10.7", features = ["psbt", "wallet"], path = "./bp-core" }
futures = "0.3"
internet2 = "0.9.0"
lnpbp = "0.9.0"
lnpbp-invoice = { version = "0.9.0", features = ["rgb"] }
miniscript = { version = "8.0", features = ["serde"] }
psbt = "0.9.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "native-tls", "stream"] }
rgb-std = "0.9.0"
rgb20 = { version = "0.10.7", path = "./rust-rgb20" }
rgb_rpc = { version = "0.9.1", path = "./rgb-node/rpc" }
serde = { version = "^1.0", features = ["derive"] }
stens = "0.9.0"
strict_encoding = "0.9.0"
thiserror = "1.0"
tokio-util = { version = "0.7.4", features = ["codec"] }

[rgb wallet]

amplify = "4.0.1"
baid58 = "0.4.4"
strict_encoding = "2.5.0"
strict_types = "1.6.0"
commit_verify = { version = "0.10.5", features = ["stl"] }
bp-core = { version = "0.10.8", features = ["stl"] }
rgb-core = { version = "0.10.7", features = ["stl"] }

[ldk]

tokio = { version = "1.14", features = [ "macros", "rt", "rt-multi-thread", "sync", "time" ] }
lightning = { version = "0.0.116", path = "../lightning", features = ["_test_utils"] }
lightning-invoice = { version = "0.24.0", path = "../lightning-invoice" }
lightning-persister = { version = "0.0.116", path = "../lightning-persister" }


bech32 = { version = "0.9.0", default-features = false }
lightning = { version = "0.0.116", path = "../lightning", default-features = false }
secp256k1 = { version = "0.24.0", default-features = false, features = ["recovery", "alloc"] }
num-traits = { version = "0.2.8", default-features = false }
bitcoin_hashes = { version = "0.11", default-features = false }
hashbrown = { version = "0.8", optional = true }
serde = { version = "1.0.118", optional = true }
bitcoin = { version = "0.29.0", default-features = false }

[dlc manager]

async-trait = "0.1.50"
bitcoin = {version = "0.29.2"}
dlc = {version = "0.4.0", path = "../dlc"}
dlc-messages = {version = "0.4.0", path = "../dlc-messages"}
dlc-trie = {version = "0.4.0", path = "../dlc-trie"}
lightning = {version = "0.0.116" }
log = "0.4.14"
rand_chacha = {version = "0.3.1", optional = true}
secp256k1-zkp = {version = "0.7.0", features = ["bitcoin_hashes", "rand", "rand-std"]}
serde = {version = "1.0", optional = true}


bitcoin-rpc-provider = {path = "../bitcoin-rpc-provider"}
bitcoin-test-utils = {path = "../bitcoin-test-utils"}
bitcoincore-rpc = {version = "0.16.0"}
bitcoincore-rpc-json = {version = "0.16.0"}
criterion = "0.4.0"
dlc-manager = {path = ".", features = ["use-serde"]}
dlc-messages = {path = "../dlc-messages", features = ["serde"]}
electrs-blockchain-provider = {path = "../electrs-blockchain-provider"}
env_logger = "0.9.1"
mocks = {path = "../mocks"}
secp256k1-zkp = {version = "0.7.0", features = ["bitcoin_hashes", "rand", "rand-std", "global-context", "use-serde"]}
serde = "1.0"
serde_json = "1.0"
simple-wallet = {path = "../simple-wallet"}

[dlc message]


bitcoin = {version = "0.29.2"}
dlc = {version = "0.4.0", path = "../dlc"}
lightning = {version = "0.0.116" }
secp256k1-zkp = {version = "0.7.0", features = ["bitcoin_hashes", "rand", "rand-std"]}
serde = {version = "1.0", features = ["derive"], optional = true}

[baid58]
base58 = "0.2.0"
blake3 = "1.4.1"
mnemonic = "1.0.1"
sha2 = "0.10.7"

[strict encoding]

amplify = { version = "4.0.0", features = ["proc_attr"] }
strict_encoding_derive = { version = "2.0.0", path = "derive" }
half = { version = "~2.2.0", optional = true } # Required to maintain MSRV
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }


[aluvm dependencies]
amplify = { version = "4.0.0", default-features = false, features = ["apfloat", "derive", "hex"] }
paste = "1"
strict_encoding = { version = "2.5.0", default-features = false, features = ["float", "derive"] }
strict_types = { version = "1.6.0", optional = true }
sha2 = "0.10.6"
ripemd = "0.1.3"
baid58 = "0.4.1"
secp256k1 = { version = "0.27.0", optional = true, features = ["global-context"] }
curve25519-dalek = { version = "3.2", optional = true }
half = "~2.2.0" # Required to maintain MSRV
serde_crate = { package = "serde", version = "1", optional = true }

[bp-std dependencies]

amplify = "4.0.1"
bitcoin_hashes = "0.12.0"
bech32 = "0.9.1"
bp-primitives = "0.10.7"
serde_crate = { package = "serde", version = "1", features = ["derive"] }
serde_with = "3.1.0"

[payjoin dependencies]
anyhow = "1.0.70"
base64 = "0.21.2"
bip21 = "0.3.1"
bitcoincore-rpc = "0.17.0"
clap = "4.1.4"
config = "0.13.3"
env_logger = "0.10.0"
log = "0.4.7"
reqwest = { version = "0.11.4", features = ["blocking"] }
rcgen = { version = "0.11.1", optional = true }
serde = { version = "1.0.160", features = ["derive"] }
payjoin = { version = "0.9.0", features = ["send", "receive", "rand"] }

[lnp dependencies]

amplify = "3.13.0"
strict_encoding = "0.9.0"
lightning_encoding = "0.9.3"
bitcoin_scripts = "0.9.0"
descriptor-wallet = { version = "0.9.0", features = ["keygen"] }
lnp2p = { version = "0.9.1", path = "lnp2p", default-features = false }
lnpbp = "0.9.0"
bitcoin = { version = "0.29.2", features = ["rand"] }
secp256k1 = { version = "0.24.2", features = ["global-context-less-secure"] }
internet2 = { version = "0.9.0-rc.1", default-features = false, features = ["keygen"] }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.14", features = ["hex"], optional = true }

[patch.crates-io]
bp-core = {  path = "./bp-core" }
bp-seals = { path = "./bp-core/seals" }
commit_verify = { path = "./client_side_validation/commit_verify" }
lightning = { path = "./rust-lightning/lightning" }
lightning-background-processor = { path = "./rust-lightning/lightning-background-processor"}
rgb20 = { path = "./rust-rgb20" }
rgb_core = { package = "rgb-core", path = "./rgb-core" }
rgb_rpc = { path = "./rgb-node/rpc" }

[bp dependencies]
amplify = "4.0.1"
bitcoin_hashes = "0.12.0"
bech32 = "0.9.1"
bp-primitives = "0.10.7"
serde_crate = { package = "serde", version = "1", features = ["derive"] }
serde_with = "3.1.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"


[patch.crates-io]
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "consensus" }


